
# .github/workflows/ci_cd.yml

name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run main file
      run: |
        python main.py
    
    - name: Run Tests
      run: |
        python -m unittest discover
    
## Only CML specefic code
    - name: Install CML
      run: |
        npm install -g @dvcorg/cml
    
    - name: Create CML report
      env:
        REPO_TOKEN: ${{ secrets.CI_SECRET }}
      run: |

        echo "# First Line of our report" >> report.md
        echo "## Bar Plots" >> report.md
        echo '![](./bar_chart.png "Bar plot")' >> report.md
        echo "## Line Plots" >> report.md
        echo '![](./line_chart.png "Bar plot")' >> report.md

        cml comment create report.md
